/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/administrator/': RouteRecordInfo<
      '/administrator/',
      '/administrator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/administrator/api-management/': RouteRecordInfo<
      '/administrator/api-management/',
      '/administrator/api-management',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/administrator/api-management/dialog': RouteRecordInfo<
      '/administrator/api-management/dialog',
      '/administrator/api-management/dialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/administrator/menu/': RouteRecordInfo<
      '/administrator/menu/',
      '/administrator/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/administrator/menu/dialog': RouteRecordInfo<
      '/administrator/menu/dialog',
      '/administrator/menu/dialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/administrator/role/': RouteRecordInfo<
      '/administrator/role/',
      '/administrator/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/administrator/role/dialog': RouteRecordInfo<
      '/administrator/role/dialog',
      '/administrator/role/dialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/administrator/user/': RouteRecordInfo<
      '/administrator/user/',
      '/administrator/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/administrator/user/menu1': RouteRecordInfo<
      '/administrator/user/menu1',
      '/administrator/user/menu1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/table': RouteRecordInfo<
      '/table',
      '/table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/administrator/index.vue': {
      routes:
        | '/administrator/'
      views:
        | never
    }
    'src/pages/administrator/api-management/index.vue': {
      routes:
        | '/administrator/api-management/'
      views:
        | never
    }
    'src/pages/administrator/api-management/dialog.vue': {
      routes:
        | '/administrator/api-management/dialog'
      views:
        | never
    }
    'src/pages/administrator/menu/index.vue': {
      routes:
        | '/administrator/menu/'
      views:
        | never
    }
    'src/pages/administrator/menu/dialog.vue': {
      routes:
        | '/administrator/menu/dialog'
      views:
        | never
    }
    'src/pages/administrator/role/index.vue': {
      routes:
        | '/administrator/role/'
      views:
        | never
    }
    'src/pages/administrator/role/dialog.vue': {
      routes:
        | '/administrator/role/dialog'
      views:
        | never
    }
    'src/pages/administrator/user/index.vue': {
      routes:
        | '/administrator/user/'
      views:
        | never
    }
    'src/pages/administrator/user/menu1.vue': {
      routes:
        | '/administrator/user/menu1'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/home/index.vue': {
      routes:
        | '/home/'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/table.vue': {
      routes:
        | '/table'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
