import { createLocalePlugin, createPermissionsPlugin } from "@vuetify/v0";
import { useStore } from "@/stores/index";
import { en, zhHans } from "vuetify/locale";

export function createMyLocalePlugin() {
  // Safe: call after Pinia is active
  const store = useStore();

  return createLocalePlugin({
    default: "cn",
    fallback: store.lang,
    messages: {
      en: {
        ...en,
        dashboard: "Dashboard",
        administrator: "Administrator",
        role: "Role",
        menu: "Menu",
        user: "User",
        apiManagement: "API Management",
        login: "Login",
        logout: "Logout",
        home: "Home",
        wellcomeBack: "Welcome back",
        email: "Email",
        password: "Password",
        rememberMe: "Remember me",
        forgotPassword: "Forgot password?",
        signIn: "Sign in",
        dontHaveAnAccount: "Don't have an account?",
        signInToContinue: "Sign in to continue",
        createOne: "Create one",
        emailIsRequired: "Email is required",
        passwordIsRequired: "Password is required",
        usernameIsRequired: "Username is required",
        username: "Username",
        notFound: "Not Found",
        search: "Search",
        areYouSure: "Are you sure?",
        yes: "Yes",
        no: "No",
        delete: "Delete",
        warning: "Warning",
        rolesManagement: "Role's Management",
        userManagement: "User's Management",
        menuManagement: "Menu's Management",
        authorityId: "Authority ID",
        authorityName: "Authority Name",
        action: "Action",
        edit: "Edit",
        create: "Create",
        save: "Save",
        cancel: "Cancel",
        add: "Add",
        update: "Update",
        submit: "Submit",
        fieldIsRequired: "Field is required",
        parent: "Parent",
        children: "children",
        child: "Child",
        rootRole: "Root role (current user role in strict mode)",
        mustBeANumber: "Must be number",
        confirm: "Confirm",
        deleteSuccess: "Deleted Success!",
        deleteFailed: "Deleted Failed!",
        updateSuccess: "Updated Success!",
        updateFailed: "Updated Failed!",
        createSuccess: "Created Success!",
        createFailed: "Created Failed!",
        roleConfiguration: "Role Configuration",
        resourcePermission: "Resource Permission",
        apiPath: "API Path",
        apiDescription: "API Description",
        apiGroup: "API Group",
        id: "ID",
        description: "Description",
        method: "Method",
        refresh: "Refresh",
        path: "Path",
        view: "View",
        nickName: "Nick name",
        phone: "Phone number",
        itemsPerPage: "Items per page",
        page: "Page",
        showing: "Showing",
        items: "Items",
        of: "of",
        total: "Total",
        usersManagement: "Users Management",
        userRole: 'User Role',
        uploadImage: "Upload Image",
        itMustBeAValidEmailAdress: "It must be a valid email adress",
        enable: "Enable",
        disable: "Disable",
      },
      cn: {
        ...zhHans,
        dashboard: "仪表盘",
        administrator: "管理员",
        role: "角色",
        menu: "菜单",
        user: "用户",
        apiManagement: "API 管理",
        login: "登录",
        logout: "退出",
        home: "首页",
        wellcomeBack: "欢迎回来",
        email: "邮箱",
        password: "密码",
        rememberMe: "记住我",
        forgotPassword: "忘记密码?",
        signIn: "登录",
        dontHaveAnAccount: "还没有账号?",
        signInToContinue: "登录继续",
        createOne: "创建账号",
        emailIsRequired: "邮箱是必填项",
        passwordIsRequired: "密码是必填项",
        usernameIsRequired: "用户名是必填项",
        username: "用户名",
        notFound: "找不到页面",
        search: "搜索",
        areYouSure: "你确定吗?",
        yes: "是",
        no: "否",
        delete: "删除",
        warning: "警告",
        rolesManagement: "角色管理",
        userManagement: "用户管理",
        menuManagement: "菜单管理",
        authorityId: "权限ID",
        authorityName: "权限名称",
        action: "操作",
        edit: "编辑",
        create: "创建",
        save: "保存",
        cancel: "取消",
        add: "添加",
        update: "更新",
        submit: "提交",
        fieldIsRequired: "字段是必填项",
        parent: "父级角色",
        children: "子级角色",
        child: "子级角色",
        rootRole: "根角色(严格模式下为当前用户角色)",
        mustBeANumber: "必须是数字",
        confirm: "确认",
        deleteSuccess: "删除成功!",
        deleteFailed: "删除失败!",
        updateSuccess: "更新成功!",
        updateFailed: "更新失败!",
        createSuccess: "创建成功!",
        createFailed: "创建失败!",
        roleConfiguration: "角色配置",
        resourcePermission: "资源权限",
        apiPath: "API 路径",
        apiDescription: "API 描述",
        apiGroup: "API 分组",
        id: "ID",
        description: "描述",
        method: "方法",
        refresh: "刷新",
        path: "路径",
        view: "查看",
        nickName: "昵称",
        phone: "手机号",
        itemsPerPage: "每页条数",
        page: "页码",
        showing: "显示",
        items: "条",
        of: "共",
        total: "条",
        usersManagement: "用户管理",
        userRole: '用户角色',
        uploadImage: "上传图片",
        itMustBeAValidEmailAdress: "必须是有效的邮箱地址",
        enable: "启用",
        disable: "禁用",
      },
    },
  });
}

export function createMyPermissionsPlugin() {
  return createPermissionsPlugin({
    permissions: {
      admin: [
        [["read", "write"], "user", true],
        [["read", "write"], "post", true],
        ["delete", ["user", "post"], true],
      ],
      editor: [
        [["read", "write"], "post", true],
        ["read", "user", true],
        [
          "delete",
          "post",
          (context: Record<string, string>) => context.isOwner,
        ],
      ],
      viewer: [["read", ["user", "post"], true]],
    },
  });
}
