import { createLocalePlugin, createPermissionsPlugin } from "@vuetify/v0";
import { useStore } from "@/stores/index";
import { en, zhHans } from "vuetify/locale";

export function createMyLocalePlugin() {
  // Safe: call after Pinia is active
  const store = useStore();

  return createLocalePlugin({
    default: "cn",
    fallback: store.lang,
    messages: {
      en: {
        ...en,
        dashboard: "Dashboard",
        administrator: "Administrator",
        role: "Role",
        menu: "Menu",
        user: "User",
        apiManagement: "API Management",
        login: "Login",
        logout: "Logout",
        home: "Home",
        wellcomeBack: "Welcome back",
        email: "Email",
        password: "Password",
        rememberMe: "Remember me",
        forgotPassword: "Forgot password?",
        signIn: "Sign in",
        dontHaveAnAccount: "Don't have an account?",
        signInToContinue: "Sign in to continue",
        createOne: "Create one",
        emailIsRequired: "Email is required",
        passwordIsRequired: "Password is required",
        usernameIsRequired: "Username is required",
        username: "Username",
        notFound: "Not Found",
        search: "Search",
        areYouSure: "Are you sure?",
        yes: "Yes",
        no: "No",
        delete: "Delete",
        warning: "Warning",
        rolesManagement: "Role's Management",
        userManagement: "User's Management",
        menuManagement: "Menu's Management",
        authorityId: "Authority ID",
        authorityName: "Authority Name",
        action: "Action",
        edit: "Edit",
        create: "Create",
        save: "Save",
        cancel: "Cancel",
        add: "Add",
        update: "Update",
        submit: "Submit",
        fieldIsRequired: "Field is required",
        parent: "Parent",
        children: "children",
        child: "Child",
        rootRole: "Root role (current user role in strict mode)",
        mustBeANumber: "Must be number",
        confirm: "Confirm",
        deleteSuccess: "Deleted Success!",
        deleteFailed: "Deleted Failed!",
        updateSuccess: "Updated Success!",
        updateFailed: "Updated Failed!",
        createSuccess: "Created Success!",
        createFailed: "Created Failed!",
        roleConfiguration: "Role Configuration",
        resourcePermission: "Resource Permission",
        apiPath: "API Path",
        apiDescription: "API Description",
        apiGroup: "API Group",
        id: "ID",
        description: "Description",
        method: "Method",
        refresh: "Refresh",
        path: "Path",
        view: "View",
        nickName: "Nick name",
        phone: "Phone number",
        itemsPerPage: "Items per page",
        page: "Page",
        showing: "Showing",
        items: "Items",
        of: "of",
        total: "Total",
        usersManagement: "Users Management",
        userRole: "User Role",
        uploadImage: "Upload Image",
        itMustBeAValidEmailAdress: "It must be a valid email adress",
        enable: "Enable",
        disable: "Disable",
        dataAnalysis: "Data Analysis",
        applicationManagement: "Application Management",
        channelManagement: "Channel Management",
        pleaseUploadImage: "Please upload Image!",
        applicationName: "Application Name",
        applicationIdentifier: "Application Identifier",
        createDate: "Create Date",
        updateDate: "Update Date",
        startDate: "Start Date",
        endDate: "End Date",
        promotionalLink: "Promotional Link",
        status: "Status",
        operation: "Operation",
        operate: "operate",
        promoteLink: "Promote Link",
        logo: "Logo",
        saveSuccess: "Save Success!",
        channel: "Channel",
        createAccount: "Create account",
        channelName: "Channel name",
        promotionType: "Promotion type",
        remark: "Remark",
        createdDate: "Created date",
        updatedDate: "Updated date",
        channelAccount: "Channel account",
        parentName: "Parent name",
        channelPromotion: "Channel Promotion",
        root: "Root",
        applicationSetting: "Application Setting",
        adposition: "Ad Position",
        adpositionManagement: "Ad Position Management",
        positionName: "Position Name",
        positionKey: "Position Key",
        advertismentManagement: "Advertisement Management",
        advertisment: "Advertisement",
        all: "All",
        pending: "Pending",
        reviewed: "Reviewed",
        rejected: "Rejected",
        adpositionName: "Adposition name",
        image: "Image",
        reviewBy: "Review by",
        totalClick: "Total click",
        monthlyClick: "Monthly click",
        advertisement: "Advertisement",
        product: "Product",
        productManagment: "Product Managment",
        productCode: "Product code",
        productName: "Product name",
        startPrice: "Start price",
        endPrice: "End price",
        startCommissionRate: "Start commission reate",
        endCommissionRate: "End Commission rate",
        productStatus: "Product status",
        removedFromShelves: "Remove from shelves",
        addedToShelves: "Added from shelves",
        productPrice: "Product price",
        commissionRate: "Commission rate",
        linkType: "Link type",
        productLink: "Product Link",
        productDescription: "Product description",
        pathParameter: "Path parameters",
        queryParameter: "Query parameters",
        affiliateLink: "Affiliate links",
        channelIdentification: "Channel Identification",
        channelType: "Channel Type",
        channelStatus: "Channel Status",
        contactNumber: "Contact Number",
        date: "Date",
        contactPerson: "Contact Person",
        contactPhone: "Contact Phone",
        channelCode: 'Channel Code',
      },
      cn: {
        ...zhHans,
        dashboard: "仪表盘",
        administrator: "管理员",
        role: "角色",
        menu: "菜单",
        user: "用户",
        apiManagement: "API 管理",
        login: "登录",
        logout: "退出",
        home: "首页",
        wellcomeBack: "欢迎回来",
        email: "邮箱",
        password: "密码",
        rememberMe: "记住我",
        forgotPassword: "忘记密码?",
        signIn: "登录",
        dontHaveAnAccount: "还没有账号?",
        signInToContinue: "登录继续",
        createOne: "创建账号",
        emailIsRequired: "邮箱是必填项",
        passwordIsRequired: "密码是必填项",
        usernameIsRequired: "用户名是必填项",
        username: "用户名",
        notFound: "找不到页面",
        search: "搜索",
        areYouSure: "你确定吗?",
        yes: "是",
        no: "否",
        delete: "删除",
        warning: "警告",
        rolesManagement: "角色管理",
        userManagement: "用户管理",
        menuManagement: "菜单管理",
        authorityId: "权限ID",
        authorityName: "权限名称",
        action: "操作",
        edit: "编辑",
        create: "创建",
        save: "保存",
        cancel: "取消",
        add: "添加",
        update: "更新",
        submit: "提交",
        fieldIsRequired: "字段是必填项",
        parent: "父级角色",
        children: "子级角色",
        child: "子级角色",
        rootRole: "根角色(严格模式下为当前用户角色)",
        mustBeANumber: "必须是数字",
        confirm: "确认",
        deleteSuccess: "删除成功!",
        deleteFailed: "删除失败!",
        updateSuccess: "更新成功!",
        updateFailed: "更新失败!",
        createSuccess: "创建成功!",
        createFailed: "创建失败!",
        roleConfiguration: "角色配置",
        resourcePermission: "资源权限",
        apiPath: "API 路径",
        apiDescription: "API 描述",
        apiGroup: "API 分组",
        id: "ID",
        description: "描述",
        method: "方法",
        refresh: "刷新",
        path: "路径",
        view: "查看",
        nickName: "昵称",
        phone: "手机号",
        itemsPerPage: "每页条数",
        page: "页码",
        showing: "显示",
        items: "条",
        of: "共",
        total: "条",
        usersManagement: "用户管理",
        userRole: "用户角色",
        uploadImage: "上传图片",
        itMustBeAValidEmailAdress: "必须是有效的邮箱地址",
        enable: "启用",
        disable: "禁用",
        dataAnalysis: "数据分析",
        applicationManagement: "应用管理",
        channelManagement: "渠道管理",
        pleaseUploadImage: "请上传图片!",
        applicationName: "应用名称",
        applicationIdentifier: "应用标识",
        createDate: "创建日期",
        updateDate: "更新日期",
        startDate: "开始日期",
        endDate: "结束日期",
        promotionalLink: "推广链接",
        status: "状态",
        operation: "操作",
        operate: "操作",
        promoteLink: "推广链接",
        logo: "标识",
        saveSuccess: "保存成功!",
        channel: "渠道",
        createAccount: "创建账号",
        channelName: "渠道名称",
        promotionType: "推广类型",
        remark: "备注",
        createdDate: "创建日期",
        updatedDate: "更新日期",
        channelAccount: "渠道账号",
        parentName: "父级名称",
        channelPromotion: "渠道推广",
        root: "根",
        applicationSetting: "应用设置",
        adposition: "广告位置",
        adpositionManagement: "广告位置管理",
        positionName: "位置名称",
        positionKey: "位置Key",
        advertismentManagement: "广告管理",
        advertisment: "广告",
        all: "全部",
        pending: "待审核",
        reviewed: "已审核",
        rejected: "已驳绝",
        adpositionName: "广告位置名称",
        image: "图片",
        reviewBy: "审核人",
        totalClick: "总点击量",
        monthlyClick: "月点击量",
        advertisement: "广告",
        product: "产品管理",
        productManagment: "产品管理",
        productCode: "产品编码",
        productName: "产品名称",
        startPrice: "开始价格",
        endPrice: "结束价格",
        startCommissionRate: "开始佣金比例",
        endCommissionRate: "结束佣金比例",
        productStatus: "产品状态",
        removedFromShelves: "下架",
        addedToShelves: "上架",
        productPrice: "产品价格",
        commissionRate: "佣金比例",
        linkType: "链接类型",
        productLink: "产品链接",
        productDescription: "产品描述",
        pathParameter: "路径参数",
        queryParameter: "查询参数",
        affiliateLink: "联盟链接",
        channelIdentification: "渠道标识",
        channelType: "渠道类型",
        channelStatus: "渠道状态",
        contactNumber: "联系电话",
        date: "日期",
        contactPerson: "联系人",
        contactPhone: "联系电话",
        channelCode: '渠道编码',
      },
    },
  });
}

export function createMyPermissionsPlugin() {
  return createPermissionsPlugin({
    permissions: {
      admin: [
        [["read", "write"], "user", true],
        [["read", "write"], "post", true],
        ["delete", ["user", "post"], true],
      ],
      editor: [
        [["read", "write"], "post", true],
        ["read", "user", true],
        [
          "delete",
          "post",
          (context: Record<string, string>) => context.isOwner,
        ],
      ],
      viewer: [["read", ["user", "post"], true]],
    },
  });
}
